name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Bundle install
      run: bundle install
      
    - name: Build and Tests
      run: chmod +x ./.github/scripts/test_app.sh 
           |
           exec ./.github/scripts/test_app.sh
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.5.2
